#apiVersion: tekton.dev/v1beta1
#kind: PipelineRun
#metadata:
#  name: sample-ocp-app-init
#  labels:
#    backstage.io/kubernetes-id: sample-ocp-app
#spec:
#  params:
#    - name: git-revision
#      value: master
#  pipelineRef:
#    name: sample-ocp-app
#  serviceAccountName: pipeline
#  workspaces:
#    - name: source-dir
#      volumeClaimTemplate:
#        spec:
#          accessModes:
#            - ReadWriteOnce
#          resources:
#            requests:
#              storage: 1Gi
#    - name: sonar-settings
#      secret:
#        secretName: sonarqube-secret-token
#    - configMap:
#        name: maven-settings
#      name: maven_settings
